name: dentalistasyon
description: "Dentalistasyon, Türkiye'deki hastaneler ve doktorlar ile tıbbi malzeme depolarını bağlayan bir hizmet sunmaktadır. Bu uygulama, sağlık sektöründeki tedarik süreçlerini kolaylaştırarak, medikal ürünlerin güvenli ve hızlı bir şekilde temin edilmesini sağlar."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rename: ^3.0.2
  get: ^4.7.2
  jiffy: ^6.3.2
  shared_preferences: ^2.5.2
  fluttericon: ^2.0.0
  flutter_onboarding_slider: ^1.0.11
  package_info_plus: ^8.2.1
  font_awesome_flutter: ^10.8.0
  themed: ^8.1.0
  awesome_dialog: ^3.2.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  http: ^1.3.0
  flutter_otp_text_field: ^1.4.0+2
  path: ^1.9.1
  device_info_plus: ^11.3.2
  flutter_datetime_picker_plus: ^2.2.0
  share_plus: ^10.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/categories/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/tu/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/tu/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/tu/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/tu/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/tu/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tu/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/tu/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tu/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/tu/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/tu/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/tu/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/tu/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/tu/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/tu/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/tu/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/tu/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/tu/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/tu/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
